-- MySQL Script generated by MySQL Workbench
-- MVT 13:01:08 2016 އޮގަސްޓް 23 އަންގާރަ
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sellers` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sellers_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_sellers_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listings` (
  `id` INT NOT NULL,
  `sellers_id` INT NOT NULL,
  `sellers_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_listings_sellers1_idx` (`sellers_id` ASC, `sellers_users_id` ASC),
  CONSTRAINT `fk_listings_sellers1`
    FOREIGN KEY (`sellers_id` , `sellers_users_id`)
    REFERENCES `mydb`.`sellers` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categories_id`),
  INDEX `fk_categories_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id` INT NULL,
  `listings_id` BIGINT NOT NULL AUTO_INCREMENT,
  `categories_id` INT NOT NULL,
  `status` ENUM('sold', 'delivered', 'hold') NULL,
  `created_at` DATETIME NULL,
  `dedede` DECIMAL(10,5) NULL,
  `uniiiiiii` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_listings1_idx` (`listings_id` ASC, `categories_id` ASC),
  INDEX `fk_items_categories1_idx` (`categories_id` ASC),
  UNIQUE INDEX `uniiiiiii_UNIQUE` (`uniiiiiii` ASC),
  CONSTRAINT `fk_items_listings1`
    FOREIGN KEY (`listings_id` , `categories_id`)
    REFERENCES `mydb`.`listings` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id` INT NOT NULL,
  `caption` VARCHAR(225) NULL,
  `url` VARCHAR(45) NULL,
  `order` INT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`, `items_id`),
  INDEX `fk_images_items1_idx` (`items_id` ASC),
  CONSTRAINT `fk_images_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`scales` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`features` (
  `id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `categories_categories_id` INT NOT NULL,
  `scales_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categories_id`, `categories_categories_id`),
  INDEX `fk_features_categories1_idx` (`categories_id` ASC, `categories_categories_id` ASC),
  INDEX `fk_features_scales1_idx` (`scales_id` ASC),
  CONSTRAINT `fk_features_categories1`
    FOREIGN KEY (`categories_id` , `categories_categories_id`)
    REFERENCES `mydb`.`categories` (`id` , `categories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_features_scales1`
    FOREIGN KEY (`scales_id`)
    REFERENCES `mydb`.`scales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`units` (
  `id` INT NOT NULL,
  `scales_id` INT NOT NULL,
  PRIMARY KEY (`id`, `scales_id`),
  INDEX `fk_units_scales1_idx` (`scales_id` ASC),
  CONSTRAINT `fk_units_scales1`
    FOREIGN KEY (`scales_id`)
    REFERENCES `mydb`.`scales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items_features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items_features` (
  `items_id` INT NOT NULL,
  `features_id` INT NOT NULL,
  `units_id` INT NOT NULL,
  PRIMARY KEY (`items_id`, `features_id`),
  INDEX `fk_items_features_features1_idx` (`features_id` ASC),
  INDEX `fk_items_features_units1_idx` (`units_id` ASC),
  CONSTRAINT `fk_items_features_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_features_features1`
    FOREIGN KEY (`features_id`)
    REFERENCES `mydb`.`features` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_features_units1`
    FOREIGN KEY (`units_id`)
    REFERENCES `mydb`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
